### ISSUE TITLE
Not working the TextureLoader demo in unity ... help

### ISSUE THREAD

**Issue by amitkumbhar14** [liushijian2ideal/TextureLoader#2]
Im getting this error below .... ( checked in editor and android pie phone )

This could only be used on Android!
UnityEngine.Debug:LogWarning(Object)
TextureLoaderPlugin:Init() (at Assets/IVRTools/TextureLoader/Scripts/TextureLoaderPlugin.cs:97)
CubeTest:Awake() (at Assets/IVRTools/TextureLoader/Examples/Scripts/CubeTest.cs:20)

**Comment by catoxliu** [comment]
That debug info will be generated if the preprocessor directives not math:

#if UNITY_ANDROID && !UNITY_EDITOR

so, make sure you build it right and run it on Android.
